 version: '3'
 services:
   db:
     image: postgres
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     environment:
      - POSTGRES_USER=pgdbuser
      - POSTGRES_PASSWORD=pgdbpass
     ports:
       - "5432:5432"
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
     ports:
       - "5672:5672"
       - "15672:15672"
 volumes:
  dvapgdata:
  dvarabbit:

