 version: '3'
 services:
   db:
     image: postgres
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     environment:
      - POSTGRES_USER=pgdbuser
      - POSTGRES_PASSWORD=pgdbpass
   rabbit:
     image: rabbitmq
     container_name: dva-rmq
     environment:
       - RABBITMQ_DEFAULT_USER=dvauser
       - RABBITMQ_DEFAULT_PASS=localpass
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   dva:
     image: akshayubhat/dva:gpu
     container_name: dva-server
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - GPU_AVAILABLE=1
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - LAUNCH_SERVER_NGINX=1
       - LAUNCH_Q_qindexer=1
       - LAUNCH_Q_qretriever=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_Q_qdetector=1
       - LAUNCH_Q_qfaceretriever=1
       - LAUNCH_Q_qfacedetector=1
       - LAUNCH_Q_qclusterer=1
       - LAUNCH_Q_qtrainer=1
       - TEST=1
       - AUTH_DISABLED=1
     command: bash -c "youtube-dl -U && git pull && fab start_container"
     ports:
       - "8000:80"
       - "8888:8888"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
   dva-ocr:
     image: akshayubhat/dva_ctpn:latest
     container_name: dva-ocr
     environment:
       - DOCKER_MODE=true
       - RABBIT_HOST=rabbit
       - RABBIT_USER=dvauser
       - RABBIT_PASS=localpass
       - GPU_AVAILABLE=1
       - DB_HOST=db
       - DB_NAME=postgres
       - DB_USER=pgdbuser
       - DB_PASS=pgdbpass
       - TEST=1
       - AUTH_DISABLED=1
     command: bash -c "sleep 60 && git pull && fab startq:qocr"
     depends_on:
       - db
       - rabbit
     volumes:
       - dvadata:/root/DVA/dva/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:

